### ISSUE TITLE
error with dexie

### ISSUE THREAD

**Issue by paulvanbladel** [kaorun343/vue-typescript-example-2#1]
Looks very nice but small error during startup:
ERROR in E:\github3rdParty\vue-typescript-example-2\node_modules\dexie\dist\dexie.d.ts
(133,19): error TS2304: Cannot find name 'Symbol'.

ERROR in E:\github3rdParty\vue-typescript-example-2\node_modules\dexie\dist\dexie.d.ts
(195,27): error TS2304: Cannot find name 'Iterable'.

ERROR in E:\github3rdParty\vue-typescript-example-2\node_modules\dexie\dist\dexie.d.ts
(196,25): error TS2304: Cannot find name 'Iterable'.

**Comment by kaorun343** [comment]
I've fixed this error. I updated `tsconfig.json` and then errors went away.
Also, I changed and updated a lot.
Thanks.

**Comment by paulvanbladel** [comment]
Thank you very much.
